name: test-and-deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
      env:
        CI: true
    - name: Build project
      run: npm run build
  upload-docker:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: covclear/web
          dockerfile: ./deployment/Dockerfile
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
  deploy-production:
    runs-on: ubuntu-latest
    needs: [test, upload-docker]
    if: github.ref == 'refs/heads/master'
    env:
      AWS_REGION: eu-west-1
      EKS_CLUSTER_NAME: cov-clear
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup kubeconfig
        run: aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
      - name: Deploy UK environment
        env:
          K8S_YAML_DIR: ./deployment/manifests
          COUNTRY: uk
        run: |
          cd $K8S_YAML_DIR
          ./render_manifests.sh "$COUNTRY" "sha-$(git rev-parse --short ${{ github.sha }})" | kubectl apply -f -
          kubectl --namespace $COUNTRY rollout status deployments.apps/frontend
      - name: Deploy EE environment
        env:
          K8S_YAML_DIR: ./deployment/manifests
          COUNTRY: ee
        run: |
          cd $K8S_YAML_DIR
          ./render_manifests.sh "$COUNTRY" "sha-$(git rev-parse --short ${{ github.sha }})" | kubectl apply -f -
          kubectl --namespace $COUNTRY rollout status deployments.apps/frontend
